"""
Seed Generator — LLM-powered fuzzing seed generation for uncovered code paths.

Uses LLM to analyze coverage gaps and generate targeted test inputs that bypass
complex require/assert guards and reach deep contract states.

This is a key component of PRISM's multi-feedback loop:
    GNN hotspots → Fuzzer → Coverage gaps → Seed Generator → new seeds → Fuzzer
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class GeneratedSeed:
    """A fuzzing seed generated by the LLM."""

    function_name: str
    inputs: dict[str, Any]
    description: str = ""
    rationale: str = ""
    target_branch: str = ""
    priority: float = 1.0  # Higher = more important to test


@dataclass
class SeedBatch:
    """A batch of generated seeds from one LLM call."""

    seeds: list[GeneratedSeed] = field(default_factory=list)
    coverage_target: float = 0.0
    iteration: int = 0
    raw_response: str = ""


# Edge-case value generators for common Solidity types
EDGE_CASE_VALUES = {
    "uint256": [0, 1, 2, 2**128, 2**255, 2**256 - 1, 10**18, 10**6],
    "uint8": [0, 1, 127, 128, 255],
    "int256": [0, 1, -1, -(2**255), 2**255 - 1],
    "address": [
        "0x0000000000000000000000000000000000000000",
        "0x000000000000000000000000000000000000dEaD",
        "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF",
    ],
    "bool": [True, False],
    "bytes32": ["0x" + "00" * 32, "0x" + "ff" * 32],
}


class SeedGenerator:
    """
    Generates fuzzing seeds using LLM analysis of coverage gaps.

    Supports both LLM-powered generation and rule-based fallback.
    """

    def __init__(self, llm: Any | None = None):
        """
        Args:
            llm: LLM client (LocalLLM, MockLLM, or LLMAuditor instance).
                 If None, uses rule-based generation only.
        """
        self.llm = llm

    def generate(
        self,
        source_code: str,
        coverage_pct: float,
        uncovered_branches: list[dict],
        hotspots: list[dict] | None = None,
        num_seeds: int = 5,
        iteration: int = 0,
    ) -> SeedBatch:
        """
        Generate fuzzing seeds for uncovered branches.

        Args:
            source_code: Contract source code (may be masked).
            coverage_pct: Current coverage percentage.
            uncovered_branches: List of uncovered functions/branches.
            hotspots: GNN-identified hotspot functions.
            num_seeds: Number of seeds to generate.
            iteration: Current feedback loop iteration.

        Returns:
            SeedBatch with generated seeds.
        """
        batch = SeedBatch(coverage_target=coverage_pct, iteration=iteration)

        if self.llm:
            try:
                batch = self._generate_with_llm(
                    source_code,
                    coverage_pct,
                    uncovered_branches,
                    hotspots or [],
                    num_seeds,
                )
                batch.iteration = iteration
                logger.info(f"LLM generated {len(batch.seeds)} seeds (iter={iteration})")
            except Exception as e:
                logger.warning(f"LLM seed generation failed: {e}. Using rule-based fallback.")
                batch = self._generate_rule_based(
                    source_code,
                    uncovered_branches,
                    hotspots or [],
                    num_seeds,
                )
                batch.iteration = iteration
        else:
            batch = self._generate_rule_based(
                source_code,
                uncovered_branches,
                hotspots or [],
                num_seeds,
            )
            batch.iteration = iteration

        return batch

    def _generate_with_llm(
        self,
        source_code: str,
        coverage_pct: float,
        uncovered_branches: list[dict],
        hotspots: list[dict],
        num_seeds: int,
    ) -> SeedBatch:
        """Generate seeds using LLM analysis."""
        # Build prompt
        prompt = self._build_seed_prompt(
            source_code,
            coverage_pct,
            uncovered_branches,
            hotspots,
            num_seeds,
        )

        system_prompt = (
            "You are a smart contract fuzzing expert. Generate test inputs as JSON.\n"
            "Each seed should have: function_name, inputs (dict), description, rationale.\n"
            "Respond ONLY with a JSON array of seed objects."
        )

        # Query LLM
        if hasattr(self.llm, "chat"):
            response = self.llm.chat(prompt, system_prompt)
            raw = response.content
        elif hasattr(self.llm, "_query"):
            raw = self.llm._query(system_prompt, prompt)
        else:
            raise ValueError("LLM client has no chat or _query method")

        # Parse response
        batch = SeedBatch(raw_response=raw, coverage_target=coverage_pct)
        batch.seeds = self._parse_llm_seeds(raw)
        return batch

    def _generate_rule_based(
        self,
        source_code: str,
        uncovered_branches: list[dict],
        hotspots: list[dict],
        num_seeds: int,
    ) -> SeedBatch:
        """Generate seeds using rule-based heuristics (no LLM needed)."""
        batch = SeedBatch()
        seeds: list[GeneratedSeed] = []

        # Priority 1: Target uncovered functions
        for branch in uncovered_branches[:num_seeds]:
            func_name = branch.get("function", branch.get("name", "unknown"))
            seeds.extend(self._generate_edge_cases(func_name, source_code))

        # Priority 2: Target hotspot functions
        for hotspot in hotspots[:num_seeds]:
            func_name = hotspot.get("function_name", "")
            vuln_hint = hotspot.get("vulnerability_hint", "").lower()
            seeds.extend(self._generate_vuln_specific_seeds(func_name, vuln_hint))

        # Priority 3: Common attack patterns
        seeds.extend(self._generate_attack_patterns(source_code))

        # Deduplicate and limit
        seen = set()
        unique_seeds = []
        for s in seeds:
            key = (s.function_name, str(s.inputs))
            if key not in seen:
                seen.add(key)
                unique_seeds.append(s)

        batch.seeds = unique_seeds[: num_seeds * 2]  # Allow some extra
        return batch

    def _generate_edge_cases(self, func_name: str, source_code: str) -> list[GeneratedSeed]:
        """Generate edge-case seeds for a specific function."""
        seeds = []

        # Detect parameter types from source code
        param_types = self._extract_param_types(func_name, source_code)

        for pname, ptype in param_types.items():
            base_type = ptype.split("[")[0]  # Handle arrays
            edge_values = EDGE_CASE_VALUES.get(base_type, EDGE_CASE_VALUES.get("uint256", [0]))

            for val in edge_values[:3]:
                seeds.append(
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={pname: val},
                        description=f"Edge case: {pname}={val}",
                        rationale=f"Boundary value for {ptype}",
                        priority=0.8,
                    )
                )

        # Zero-value call
        if param_types:
            seeds.append(
                GeneratedSeed(
                    function_name=func_name,
                    inputs={k: 0 for k in param_types},
                    description="All-zero inputs",
                    rationale="Test zero-value edge case for all parameters",
                    priority=0.9,
                )
            )

        return seeds

    def _generate_vuln_specific_seeds(self, func_name: str, vuln_hint: str) -> list[GeneratedSeed]:
        """Generate seeds targeting a specific vulnerability type."""
        seeds = []

        if "reentrancy" in vuln_hint:
            seeds.extend(
                [
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"amount": 10**18, "msg.value": 10**18},
                        description="Reentrancy: deposit then withdraw full balance",
                        rationale="Test CEI pattern by withdrawing deposited amount",
                        priority=1.0,
                    ),
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"amount": 0},
                        description="Reentrancy: zero-amount withdraw",
                        rationale="Test if zero withdrawal triggers external call",
                        priority=0.7,
                    ),
                ]
            )

        elif "overflow" in vuln_hint or "integer" in vuln_hint:
            seeds.extend(
                [
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"amount": 2**256 - 1, "value": 1},
                        description="Overflow: max uint256 + 1",
                        rationale="Trigger arithmetic overflow with boundary values",
                        priority=1.0,
                    ),
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"amount": 2**255},
                        description="Overflow: half of max uint256",
                        rationale="Test near-overflow conditions",
                        priority=0.8,
                    ),
                ]
            )

        elif "access" in vuln_hint:
            seeds.extend(
                [
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"msg.sender": "0x" + "00" * 20},
                        description="Access control: call from zero address",
                        rationale="Test authorization bypass with zero address",
                        priority=1.0,
                    ),
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"msg.sender": "0x" + "ff" * 20},
                        description="Access control: call from max address",
                        rationale="Test authorization with unusual sender",
                        priority=0.8,
                    ),
                ]
            )

        elif "timestamp" in vuln_hint:
            seeds.extend(
                [
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"block.timestamp": 0},
                        description="Timestamp: genesis block time",
                        rationale="Test timestamp-dependent logic with minimal value",
                        priority=0.9,
                    ),
                ]
            )

        elif "unchecked" in vuln_hint or "return" in vuln_hint:
            seeds.extend(
                [
                    GeneratedSeed(
                        function_name=func_name,
                        inputs={"to": "0x" + "00" * 20, "amount": 10**18},
                        description="Unchecked return: transfer to zero address",
                        rationale="Force transfer failure to test return value handling",
                        priority=1.0,
                    ),
                ]
            )

        return seeds

    def _generate_attack_patterns(self, source_code: str) -> list[GeneratedSeed]:
        """Generate common smart contract attack pattern seeds."""
        seeds = []

        # Flash loan attack pattern
        if "borrow" in source_code.lower() or "flash" in source_code.lower():
            seeds.append(
                GeneratedSeed(
                    function_name="borrow",
                    inputs={"amount": 10**24},
                    description="Flash loan: large borrow amount",
                    rationale="Test flash loan attack vector with large values",
                    priority=0.9,
                )
            )

        # Self-destruct target
        if "selfdestruct" in source_code.lower():
            seeds.append(
                GeneratedSeed(
                    function_name="destroy",
                    inputs={"recipient": "0x" + "ff" * 20},
                    description="Self-destruct: force ETH to arbitrary address",
                    rationale="Test if selfdestruct can be triggered",
                    priority=1.0,
                )
            )

        # Approval front-running
        if "approve" in source_code.lower():
            seeds.append(
                GeneratedSeed(
                    function_name="approve",
                    inputs={"spender": "0x" + "ff" * 20, "amount": 2**256 - 1},
                    description="Approval: unlimited approval to suspicious address",
                    rationale="Test front-running on approve with max amount",
                    priority=0.8,
                )
            )

        return seeds

    def _extract_param_types(self, func_name: str, source_code: str) -> dict[str, str]:
        """Extract parameter names and types from source code."""
        params = {}

        # Match function signature: function funcName(type1 name1, type2 name2, ...)
        pattern = rf"function\s+{re.escape(func_name)}\s*\(([^)]*)\)"
        match = re.search(pattern, source_code)
        if match:
            param_str = match.group(1).strip()
            if param_str:
                for part in param_str.split(","):
                    tokens = part.strip().split()
                    if len(tokens) >= 2:
                        ptype = tokens[0]
                        pname = tokens[-1]  # Last token is the name
                        # Skip memory/calldata/storage keywords
                        if pname in ("memory", "calldata", "storage") and len(tokens) >= 3:
                            pname = tokens[-1]
                        params[pname] = ptype

        return params

    def _parse_llm_seeds(self, response: str) -> list[GeneratedSeed]:
        """Parse LLM response into GeneratedSeed objects."""
        seeds = []

        try:
            # Find JSON array in response
            start = response.find("[")
            end = response.rfind("]") + 1
            if start >= 0 and end > start:
                data = json.loads(response[start:end])
                for item in data:
                    if isinstance(item, dict):
                        seeds.append(
                            GeneratedSeed(
                                function_name=item.get("function_name", item.get("function", "unknown")),
                                inputs=item.get("inputs", {}),
                                description=item.get("description", ""),
                                rationale=item.get("rationale", ""),
                                priority=item.get("priority", 1.0),
                            )
                        )
        except (json.JSONDecodeError, ValueError) as e:
            logger.warning(f"Failed to parse LLM seed response: {e}")

        return seeds

    def _build_seed_prompt(
        self,
        source_code: str,
        coverage_pct: float,
        uncovered_branches: list[dict],
        hotspots: list[dict],
        num_seeds: int,
    ) -> str:
        """Build the prompt for LLM seed generation."""
        parts = [
            f"Analyze the following smart contract and generate {num_seeds} fuzzing seeds.\n",
            f"Current coverage: {coverage_pct:.1f}%\n",
        ]

        if uncovered_branches:
            parts.append("\nUncovered branches:")
            for b in uncovered_branches[:10]:
                func = b.get("function", b.get("name", "unknown"))
                parts.append(f"  - {func}")

        if hotspots:
            parts.append("\nGNN-identified hotspots:")
            for h in hotspots[:5]:
                parts.append(
                    f"  - {h.get('function_name', '')}: "
                    f"risk={h.get('risk_score', 0):.2f} "
                    f"({h.get('vulnerability_hint', '')})"
                )

        # Truncate source code if too long
        max_code_len = 8000
        code = source_code[:max_code_len]
        if len(source_code) > max_code_len:
            code += "\n... (truncated)"

        parts.append(f"\nSource code:\n```solidity\n{code}\n```")
        parts.append(
            f"\nGenerate {num_seeds} test seeds as a JSON array. "
            "Each seed: {function_name, inputs, description, rationale}"
        )

        return "\n".join(parts)
