"""
Test Harness Generator — Auto-generates Foundry/Echidna test harnesses.

Creates test contracts that wrap the target contract and expose:
- Property-based invariant tests for fuzzing
- Setup functions with realistic state
- Attack contract templates for reentrancy/access control testing
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class HarnessConfig:
    """Configuration for harness generation."""

    target_contract: str
    target_file: str
    functions: list[dict]
    hotspots: list[dict] | None = None
    include_attack_contracts: bool = True
    fuzz_runs: int = 1000


class HarnessGenerator:
    """
    Auto-generates Foundry test harnesses for smart contract fuzzing.

    Generates:
    1. Base test contract with setUp and utility functions
    2. Property-based invariant tests for each vulnerability type
    3. Attack contracts for reentrancy testing
    4. Edge-case test functions targeting hotspot functions
    """

    # Invariant templates for each vulnerability type
    INVARIANT_TESTS = {
        "reentrancy": {
            "test_name": "test_reentrancy_guard",
            "description": "Verify balance consistency after withdrawal",
            "template": """
    function test_reentrancy_{func}() public {{
        // Setup: deposit funds
        uint256 initialBalance = address(target).balance;
        vm.deal(address(this), 10 ether);

        // Action: attempt withdrawal
        try target.{func}(1 ether) {{
            // Verify: balance decreased correctly
            assertLe(address(target).balance, initialBalance);
        }} catch {{
            // Expected if no funds deposited
        }}
    }}""",
        },
        "access_control": {
            "test_name": "test_access_control",
            "description": "Verify non-owner cannot call privileged functions",
            "template": """
    function test_access_control_{func}() public {{
        // Setup: use non-owner address
        address attacker = address(0xBEEF);
        vm.prank(attacker);

        // Action: attempt to call privileged function
        vm.expectRevert();
        target.{func}();
    }}""",
        },
        "integer_overflow": {
            "test_name": "test_overflow",
            "description": "Verify arithmetic operations don't overflow",
            "template": """
    function test_overflow_{func}(uint256 amount) public {{
        // Bound input to prevent trivial cases
        amount = bound(amount, 1, type(uint256).max);

        try target.{func}(amount) {{
            // If succeeds, verify post-conditions
            assertTrue(true);
        }} catch {{
            // Overflow should revert
        }}
    }}""",
        },
        "unchecked_return": {
            "test_name": "test_return_check",
            "description": "Verify low-level call return values are checked",
            "template": """
    function test_return_check_{func}() public {{
        // Setup: create conditions for call failure
        address payable target_addr = payable(address(target));

        // Action: call with conditions that may cause failure
        try target.{func}() {{
            assertTrue(true);
        }} catch {{
            // Expected behavior - return value was checked
        }}
    }}""",
        },
    }

    def __init__(self):
        pass

    def generate(self, config: HarnessConfig) -> str:
        """Generate a complete Foundry test harness."""
        parts = [
            self._generate_header(config),
            self._generate_imports(config),
            self._generate_test_contract(config),
        ]

        if config.include_attack_contracts:
            attack = self._generate_attack_contract(config)
            if attack:
                parts.append(attack)

        return "\n\n".join(parts)

    def generate_and_save(self, config: HarnessConfig, output_dir: str | Path) -> Path:
        """Generate harness and save to file."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        harness_code = self.generate(config)
        filename = f"Test{config.target_contract}.t.sol"
        output_path = output_dir / filename

        output_path.write_text(harness_code)
        logger.info(f"Generated test harness: {output_path}")

        return output_path

    def _generate_header(self, config: HarnessConfig) -> str:
        """Generate SPDX and pragma header."""
        return (
            "// SPDX-License-Identifier: MIT\n// Auto-generated by PRISM Harness Generator\npragma solidity ^0.8.20;\n"
        )

    def _generate_imports(self, config: HarnessConfig) -> str:
        """Generate import statements."""
        return f'import "forge-std/Test.sol";\nimport "../src/{config.target_file}";'

    def _generate_test_contract(self, config: HarnessConfig) -> str:
        """Generate the main test contract."""
        lines = [
            f"contract Test{config.target_contract} is Test {{",
            f"    {config.target_contract} public target;",
            "    address public owner = address(this);",
            "    address public attacker = address(0xBEEF);",
            "    address public user1 = address(0xCAFE);",
            "",
            "    function setUp() public {",
            f"        target = new {config.target_contract}();",
            "        vm.deal(address(this), 100 ether);",
            "        vm.deal(attacker, 10 ether);",
            "        vm.deal(user1, 10 ether);",
            "    }",
            "",
            "    // ============ Receive ETH ============",
            "    receive() external payable {}",
        ]

        # Generate invariant tests based on hotspots
        hotspots = config.hotspots or []
        for hotspot in hotspots:
            func_name = hotspot.get("function_name", "")
            vuln_hint = hotspot.get("vulnerability_hint", "").lower()

            for vuln_type, template_info in self.INVARIANT_TESTS.items():
                if vuln_type in vuln_hint or vuln_hint == "":
                    test_code = template_info["template"].format(func=self._sanitize_name(func_name))
                    lines.append("")
                    lines.append(f"    // {template_info['description']}")
                    lines.append(test_code)
                    break  # One test per hotspot

        # Generate generic tests for all exposed functions
        for func in config.functions:
            func_name = func.get("name", "")
            if func_name and not func_name.startswith("_"):
                lines.extend(self._generate_function_tests(func))

        # Fuzz test (parameterized)
        lines.extend(
            [
                "",
                "    // ============ Fuzz Tests ============",
                "    function testFuzz_genericCall(uint256 amount) public {",
                "        amount = bound(amount, 0, 100 ether);",
                "        vm.deal(address(this), amount);",
                "        // Generic fuzz test - override with specific logic",
                "    }",
            ]
        )

        lines.append("}")
        return "\n".join(lines)

    def _generate_function_tests(self, func: dict) -> list[str]:
        """Generate tests for a specific function."""
        lines = []
        func_name = func.get("name", "")
        sanitized = self._sanitize_name(func_name)
        params = func.get("parameters", [])

        # Basic call test
        lines.append("")
        lines.append(f"    // Test: {func_name}")
        lines.append(f"    function test_{sanitized}_basic() public {{")

        if params:
            args = []
            for p in params:
                ptype = p.get("type", "uint256")
                pname = p.get("name", "arg")
                default = self._default_value(ptype)
                lines.append(f"        {ptype} {pname} = {default};")
                args.append(pname)
            args_str = ", ".join(args)
            lines.append(f"        target.{func_name}({args_str});")
        else:
            lines.append(f"        target.{func_name}();")

        lines.append("    }")
        return lines

    def _generate_attack_contract(self, config: HarnessConfig) -> str:
        """Generate an attack contract for reentrancy testing."""
        # Only generate if reentrancy hotspots exist
        hotspots = config.hotspots or []
        reentrant_funcs = [
            h.get("function_name", "") for h in hotspots if "reentrancy" in h.get("vulnerability_hint", "").lower()
        ]

        if not reentrant_funcs:
            return ""

        target_func = self._sanitize_name(reentrant_funcs[0])

        return f"""
// Attack contract for reentrancy testing
contract ReentrancyAttacker {{
    {config.target_contract} public target;
    uint256 public attackCount;
    uint256 public maxAttacks = 3;

    constructor(address _target) {{
        target = {config.target_contract}(_target);
    }}

    function attack() external payable {{
        // Initiate the attack by calling the vulnerable function
        target.{target_func}();
    }}

    receive() external payable {{
        // Re-enter during callback
        if (attackCount < maxAttacks) {{
            attackCount++;
            target.{target_func}();
        }}
    }}

    fallback() external payable {{
        if (attackCount < maxAttacks) {{
            attackCount++;
            target.{target_func}();
        }}
    }}
}}"""

    def _sanitize_name(self, name: str) -> str:
        """Sanitize function name for use in test names."""
        return re.sub(r"[^a-zA-Z0-9_]", "_", name)

    def _default_value(self, solidity_type: str) -> str:
        """Get default test value for a Solidity type."""
        defaults = {
            "uint256": "1 ether",
            "uint128": "1e18",
            "uint64": "1000",
            "uint32": "100",
            "uint8": "1",
            "int256": "1",
            "address": "address(0xCAFE)",
            "bool": "true",
            "bytes32": "bytes32(0)",
            "bytes": '""',
            "string": '"test"',
        }
        return defaults.get(solidity_type, "0")
